apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stalwart.fullname" . }}-config
data:
  STALWART_CONFIG: |
    [database]
    url = "${POSTGRES_URI}"

    [storage]
    data_dir = "{{ .Values.storage.data.mountPath }}"
