apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coturn.fullname" . }}
data:
  turnserver.conf: |
    realm={{ .Values.auth.realm }}
    lt-cred-mech
    use-auth-secret
    static-auth-secret=$(AUTH_SECRET)
    fingerprint

    min-port={{ .Values.network.relay.minPort }}
    max-port={{ .Values.network.relay.maxPort }}

    listening-port={{ .Values.network.controlPort }}

    no-tls
    no-dtls

    log-file=stdout
    simple-log
