apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}-udp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: turn-udp
      port: {{ .Values.network.controlPort }}
      protocol: UDP
  selector:
    app: {{ include "coturn.name" . }}
