apiVersion: v2
name: colony
description: A production-hardened Helm chart for deploying Ant Investor microservices
type: application
icon: https://raw.githubusercontent.com/antinvestor/charts/main/charts/colony/colony.png
version: 1.6.14
appVersion: "0.0.1"
keywords:
  - colony
  - microservice
  - kubernetes
maintainers:
  - name: Antinvestor Team
