{{- if .Values.externalDNS.enabled }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "colony.labels" . | nindent 4 }}
spec:
  endpoints:
    - dnsName: {{ .Values.gateway.hostname | quote }}
      recordTTL: {{ .Values.externalDNS.recordTTL }}
      recordType: {{ .Values.externalDNS.recordType }}
      targets:
        {{- toYaml .Values.externalDNS.targets | nindent 8 }}
      {{- if .Values.externalDNS.cloudflareProxied }}
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
      {{- end }}
{{- end }}
