{{- if .Values.fluxcd.enabled }}
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "colony.labels" . | nindent 4 }}
spec:
  secretRef:
    name: {{ .Values.fluxcd.imageRepository.secretRef }}
  image: {{ .Values.image.registry }}/{{ .Values.image.repository }}
  interval: {{ .Values.fluxcd.imageRepository.interval }}
{{- end }}
