{{- if .Values.fluxcd.enabled }}
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "colony.labels" . | nindent 4 }}
spec:
  imageRepositoryRef:
    name: {{ .Release.Name }}
  policy:
    semver:
      range: {{ .Values.fluxcd.imagePolicy.semver.range | quote }}
{{- end }}
