{{- if and .Values.gateway.enabled (eq .Values.gateway.type "grpc") }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "colony.labels" . | nindent 4 }}
spec:
  parentRefs:
    - kind: {{ .Values.gateway.parentRef.kind }}
      name: {{ .Values.gateway.parentRef.name }}
      namespace: {{ .Values.gateway.parentRef.namespace }}
      sectionName: {{ .Values.gateway.parentRef.sectionName }}
  hostnames:
    - {{ include "colony.gatewayHostname" . | quote }}
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.grpc.port }}
          weight: 1
{{- end }}
