apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "colony.labels" . | nindent 4 }}
  annotations:
    service.kubernetes.io/topology-mode: {{ .Values.service.topologyMode }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml .Values.service.ipFamilies | nindent 4 }}
  {{- end }}
  ports:
    {{- if .Values.service.grpc.enabled }}
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.targetPort }}
      protocol: TCP
      {{- if .Values.service.grpc.appProtocol }}
      appProtocol: {{ .Values.service.grpc.appProtocol }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.http.enabled }}
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
      {{- if .Values.service.http.appProtocol }}
      appProtocol: {{ .Values.service.http.appProtocol }}
      {{- end }}
    {{- end }}
  {{- if .Values.service.trafficDistribution }}
  trafficDistribution: {{ .Values.service.trafficDistribution }}
  {{- end }}
  selector:
    {{ include "colony.selectorLabels" . | nindent 4 }}
