apiVersion: v1
kind: Service
metadata:
  name: {{ include "colony.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "colony.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.grpc.enabled }}
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.targetPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.http.enabled }}
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "colony.selectorLabels" . | nindent 4 }}
