name: Release Charts

on:
  push:
    paths:
      - 'charts/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing the Helm charts to the gh-pages branch
      packages: write # Required for GHCR access
      id-token: write # Required for signing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Import GPG Private Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --dearmor --output /tmp/keyring.gpg
          echo "${{ secrets.GPG_KEY_PASSPHRASE }}" > /tmp/passphrase-file.txt

      - name: Set up Helm
        uses: azure/setup-helm@v4 # v4.3.1
        with:
          version: v3.16.2

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_KEY: helm-charts+info@antinvestor.com
          CR_KEYRING: /tmp/keyring.gpg
          CR_PASSPHRASE_FILE: /tmp/passphrase-file.txt
          CR_SIGN: true
          CR_SKIP_EXISTING: true
          CR_GENERATE_RELEASE_NOTES: true